name: Update Leaderboard

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  updateLeaderboard:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: npm i

      - name: Fetch updates
        run: npx tsm ./utils/updateLeaderboard.ts

      - name: Commit changes
        run: |
          git add leaderboard.csv
          git commit -m "Update leaderboard"
          git push origin main
