name: Update Leaderboard

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  updateLeaderboard:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: npm i

      - name: Fetch updates
        env:
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        run: npx tsm ./utils/updateLeaderboard.ts

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "dan.eden+bot@me.com"

      - name: Commit changes
        run: |
          git add leaderboard.csv
          git commit -m "Update leaderboard"
          git push origin main
